# Header

menu:
  主页: /
  #相册: /photos

# SubNav
subnav:
  github: "https://github.com/windzz"
  #weibo: "http://weibo.com/litten225"
  #rss: /atom.xml
  #qq: '763085631'
  #zhihu: "https://www.zhihu.com/people/windzz"
  #douban: "#"
  #segmentfault: "#"
  mail: "mailto:windzz1024@gmail.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

#rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root:

# Content
excerpt_link: 'more'
show_all_link: '展开全文'
fancybox: true
mathjax: true

# 打赏
reward_type: 1
reward_wording: '谢谢你请我吃糖果'
alipay: /assets/img/alipay.png
weixin: /assets/img/wxpay.png

# 是否在新窗口打开链接
open_in_new: true

# Miscellaneous
baidu_analytics: '40e714083c3957156625c0915c780732'
google_analytics: false
favicon: /assets/img/favicon.ico

#你的头像url
avatar: '/assets/blogImg/windzz4.png'

#是否开启分享
share_jia: true

mobile:
  social: true

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
#duoshuo: "litten-hexo"
changyan: "cysUyhexJ"

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 如不需要，将该项置为false
# 比如
#smart_menu:
  #friends: true

smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

friends:
  Litten 主题作者: http://litten.me/

aboutme: Windzz，<br>毕业于石家庄学院，就职于达令<br><br>酷爱乡村爱情，<br/>目前是一枚拍片儿的艺术家(PHP程序员)<br/><br/>踏踏实实做人,诚心诚意做事，<br/>高贵的气质源于兢兢业业，<br/>森屿暖树，墒以光年。
